name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
      - uses: ./
        with:
          configuration-path: __tests__/pr-labeler.yml
      - uses: ./
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: ./
        with:
          configuration-path: __tests__/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
